DROP DATABASE IF EXISTS `RETRIEVAL`;
CREATE DATABASE `RETRIEVAL`;

USE `RETRIEVAL`;

DROP TABLE IF EXISTS `T_NODE`;
-- 建立Node表
CREATE TABLE `T_NODE` (
	`ID`              VARCHAR(45) PRIMARY KEY,
	`CNAME`           VARCHAR(45) NOT NULL DEFAULT '',
	`ENAME`           VARCHAR(45) NOT NULL DEFAULT '',
	`URI`             VARCHAR(45) NOT NULL DEFAULT '',
	`PARENT_ID`       VARCHAR(45) NOT NULL DEFAULT '',
	`OF_PARENT_INDEX` INT(11) NOT NULL DEFAULT -1,
	`REMARK`          VARCHAR(100) NOT NULL DEFAULT '',
	`CREATOR_ID`      INT(11) NOT NULL DEFAULT -1,
	`MODIFIER_ID`     INT(11) NOT NULL DEFAULT -1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- 初始化虚拟节点
INSERT INTO `T_NODE` VALUES('VIRTUAL_NODE', 'VIRTUAL_NODE', 'VIRTUAL_NODE', '', '-1', -1, '', -1, -1);

-- 建立NodeAttribute表
DROP TABLE IF EXISTS `T_NODE_ATTRIBUTE`;
CREATE TABLE `T_NODE_ATTRIBUTE` (
	`ID`              VARCHAR(45) PRIMARY KEY,
	`ATTR_KEY`        VARCHAR(45) NOT NULL DEFAULT '',
	`ATTR_VALUE`      VARCHAR(45) NOT NULL DEFAULT '',
	`NODE_ID`         VARCHAR(45) NOT NULL DEFAULT '',
	`REMARK`          VARCHAR(100) NOT NULL DEFAULT '',
	`CREATOR_ID`      INT(11) NOT NULL DEFAULT -1,
	`MODIFIER_ID`     INT(11) NOT NULL DEFAULT -1
) ENGINE=InnoDB DEFAULT CHARSET=utf8;