DROP DATABASE IF EXISTS `RETRIEVAL`;
CREATE DATABASE `RETRIEVAL`;

USE `RETRIEVAL`;

DROP TABLE IF EXISTS `T_NODE`;
CREATE TABLE `T_NODE` (
	`ID`              VARCHAR(45) PRIMARY KEY AUTO_INCREMENT,
	`CNAME`           VARCHAR(45) NOT NULL DEFAULT '',
	`ENAME`           VARCHAR(45) NOT NULL DEFAULT '',
	`URI`             VARCHAR(45) NOT NULL DEFAULT '',
	`PARENT_ID`       VARCHAR(45) NOT NULL DEFAULT '',
	`OF_PARENT_INDEX` INT(11) NOT NULL DEFAULT -1,
	`REMARK`          VARCHAR(100) NOT NULL DEFAULT '',
	`CREATOR_ID`      INT(11) NOT NULL DEFAULT -1,
	`MODIFIER_ID`     INT(11) NOT NULL DEFAULT -1,
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `T_NODE` VALUES('VIRTUAL_NODE', 'VIRTUAL_NODE', 'VIRTUAL_NODE', '', '-1', -1, '', -1, -1);
